"""add discount, image_url, rating fields

Revision ID: cdb85441449c
Revises: 1587f3e75e00
Create Date: 2026-03-03 23:32:58.937991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdb85441449c'
down_revision: Union[str, Sequence[str], None] = '1587f3e75e00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('discount', sa.Numeric(precision=5, scale=2), nullable=False))
    op.add_column('products', sa.Column('image_url', sa.String(length=255), nullable=False))
    op.add_column('products', sa.Column('count_feedbacks', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('evaluation', sa.Numeric(precision=2, scale=1), nullable=False))
    op.drop_constraint(op.f('products_category_id_fkey'), 'products', type_='foreignkey')
    op.drop_column('products', 'category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('products_category_id_fkey'), 'products', 'categories', ['category_id'], ['id'])
    op.drop_column('products', 'evaluation')
    op.drop_column('products', 'count_feedbacks')
    op.drop_column('products', 'image_url')
    op.drop_column('products', 'discount')
    # ### end Alembic commands ###
